// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtLNjEliLOYORE9ZFWA52N3uDfzbedovw',
    appId: '1:779307522273:web:feac6b573772558a1fbfa0',
    messagingSenderId: '779307522273',
    projectId: 'flutter-auth-app-d7389',
    authDomain: 'flutter-auth-app-d7389.firebaseapp.com',
    storageBucket: 'flutter-auth-app-d7389.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIL8jZVHFzkS0hHLewbsZVYh3eg2DDrS4',
    appId: '1:779307522273:android:132eb52e57745fba1fbfa0',
    messagingSenderId: '779307522273',
    projectId: 'flutter-auth-app-d7389',
    storageBucket: 'flutter-auth-app-d7389.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeKRi-LjFBbL3PgYg3K3fWOpJ743B99i0',
    appId: '1:779307522273:ios:a733386f394937631fbfa0',
    messagingSenderId: '779307522273',
    projectId: 'flutter-auth-app-d7389',
    storageBucket: 'flutter-auth-app-d7389.firebasestorage.app',
    iosBundleId: 'com.example.flutterAuthApp',
  );
}
